In [2]:
# Este exemplo carrega a base Wine da UCI, e avalia dois KNNs
# Um usando holdout e outro usando validação cruzada com 10 pastas. 

# Importa bibliotecas necessárias 
import numpy as np
import urllib.request
from sklearn.neighbors import KNeighborsClassifier
from sklearn import  model_selection
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedShuffleSplit
import pandas as pd

# Carrega uma base de dados do UCI
# Exemplo carrega a base Wine
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
raw_data = urllib.request.urlopen(url)

# Carrega arquivo como uma matriz
dataset = np.loadtxt(raw_data, delimiter=",")

# Imprime quantide de instâncias e atributos da base
print(dataset.shape)

# Coloca em X os 13 atributos de entrada e em y as classes
# Observe que na base Wine a classe é primeiro atributo 
X = dataset[:,1:13]
y = dataset[:,0]

# EXEMPLO USANDO HOLDOUT
# Holdout -> dividindo a base em treinamento (70%) e teste (30%), estratificada
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.3, random_state=42, stratify=y)

# declara o classificador
clfa = KNeighborsClassifier(n_neighbors=3)

# treina o classificador
clfa = clfa.fit(X_train, y_train)

# testa usando a base de testes
predicted=clfa.predict(X_test)

# calcula a acurácia na base de teste
score=clfa.score(X_test, y_test)

# calcula a matriz de confusão
matrix = confusion_matrix(y_test, predicted)

# apresenta os resultados
print("Accuracy = %.5f " % score)
print("Confusion Matrix:")
print(matrix)

# EXEMPLO USANDO VALIDAÇÃO CRUZADA
clfb = KNeighborsClassifier(n_neighbors=3)
folds=10
result = model_selection.cross_val_score(clfb, X, y, cv=folds)
print("\nCross Validation Results %d folds:" % folds)
print("Mean Accuracy: %.5f" % result.mean())
print("Mean Std: %.5f" % result.std())

# matriz de confusão da validação cruzada
Z = model_selection.cross_val_predict(clfb, X, y, cv=folds)
cm=confusion_matrix(y, Z)
print("Confusion Matrix:")
print(cm)


(178, 14)
Accuracy = 0.83333 
Confusion Matrix:
[[18  0  0]
 [ 5 15  1]
 [ 2  1 12]]

Cross Validation Results 10 folds:
Mean Accuracy: 0.86503
Mean Std: 0.08343
Confusion Matrix:
[[54  5  0]
 [10 59  2]
 [ 4  3 41]]
