# Covariância e correlação


Vamos usar as bibliotecas $numpy$ e $time$.

In [1]:
import numpy as np
import pandas as pd

## Covariância
Descreve o grau de relacionamento linear entre duas variáveis aleatórias.
* $COV[X,Y]=E[X\cdot Y]-E[X]\cdot E[Y]$<br>

Valor da covariância
* Cresce com a força do relacionamento linear
* É difícil fazer julgamentos sobre o força do relacionamento observando a covariância porque ela não é uma medida padronizada


Sinal na covariância
* Indica a direção do relacionamento linear
* Sinal positivo: variam na mesma direção
* Sinal negativo: variam em direções opostas<br>

A covariância entre as variáveis $X_{1}, X_{1}, ..., X_{n}$ é dada pela matriz cujo elemento $(i, j)$ é $COV(X_{i},X_{j})$.<br>
A covariância entre um elemento $X_{i}$ e ele mesmo é a sua variância e forma a diagonal principal da matriz.<br>

$\Sigma = \begin{bmatrix}
COV[X_{1},X_{1}] & COV[X_{1},X_{2}] & \cdots  & COV[X_{1},X_{n}]\\ 
COV[X_{2},X_{1}] & COV[X_{2},X_{2}] & \cdots  & COV[X_{2},X_{n}]\\
\vdots & \ddots & \ddots & \vdots \\
COV[X_{3},X_{1}] & COV[X_{3},X_{2}] & \cdots  & COV[X_{3},X_{n}]
\end{bmatrix}$

In [2]:
# Ler dados
DadosDataCenter = pd.read_csv('./DadosDataCenter.csv')
print(DadosDataCenter.head(5))

          V1        V2         V3        V4
0  38.793707  2.394610   4.771743  0.425009
1  17.329355  3.459197   5.280938  0.568836
2  15.265747  4.330490  11.583133  0.888388
3  33.475601  2.617525   9.724039  0.841919
4  24.286244  5.093494   6.904809  0.747310


In [3]:
SIGMA = DadosDataCenter.cov()
print(SIGMA)

            V1        V2        V3        V4
V1   89.563408 -5.039661  1.520156  0.351915
 V2  -5.039661  1.372982  0.463601  0.042089
 V3   1.520156  0.463601  7.141279  0.385457
 V4   0.351915  0.042089  0.385457  0.030950


In [4]:
sigma = SIGMA.to_numpy()

In [5]:
print(sigma)

[[ 8.95634081e+01 -5.03966114e+00  1.52015637e+00  3.51915201e-01]
 [-5.03966114e+00  1.37298158e+00  4.63601104e-01  4.20892797e-02]
 [ 1.52015637e+00  4.63601104e-01  7.14127859e+00  3.85457111e-01]
 [ 3.51915201e-01  4.20892797e-02  3.85457111e-01  3.09498140e-02]]
